# -*- coding: utf-8 -*-
"""task03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bNSTiEKXryEc54XjyZU5BLPptAky2mPW
"""

book1=open("Book1.txt",'r')
book10=book1.read().split()
book2=open("Book2.txt",'r')
book3=open("Book3.txt",'r')
book4=open("20k.txt",'r')
book40=book4.read().split()
list1=[]
list2=[]
def unique_word():
  for i in book10:
    if i in book40:
      if i in list1:
        continue
      else:
        list1.append(i)
    else:
      list1.append(i)
  print(list1)
unique_word()

def count_the_article():
  dic={}
  for i in book10:
    list2.append(i)

  print(list2)
  for m in list2:
    if m in dic.keys():
      count = dic[m] + 1
      dic[m] = count
    else:
      dic[m] = 1
  for word in book40:
    if word in dic.keys():
      print(word,dic[word])
    
count_the_article()

def sorted_word():
  list1=[]
  for i in book10:
    list1.append(book10)
  list1.sort()
  print(list1)
sorted_word()

def character_word_count():
  dic={}
  for i in book10:
    list1.append(i)

  print(list1)
  for m in list1:
    if m in dic.keys():
      count = dic[m] + 1
      dic[m] = count
    else:
      dic[m] = 1

  print(dic)
character_word_count()

()