# -*- coding: utf-8 -*-
"""task01.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Gqftch5ll3CdBlU6mNLGNI4skOm1Fw-
"""

import pandas as pd
import sys
import csv

book=open("Trails.csv","r")
book_1=pd.read_csv("Trails.csv")
#print("File before operation : ", book_1)
book_1.sort_values(["CONDITION","OBJECTID"],axis=0,ascending=True,inplace=True,na_position='first')
#print(book_1)
good = book_1[(book_1['CONDITION'] == 'GOOD')]
nan = book_1[(book_1['CONDITION'] == ' ')]
marginal = book_1[(book_1['CONDITION'] == 'MARGINAL')]
poor = book_1[(book_1['CONDITION'] == 'POOR')]
# 1
list_good = good["TRAIL_NAME"]
list_nan = nan["TRAIL_NAME"]
list_marginal = marginal["TRAIL_NAME"]
list_poor = poor["TRAIL_NAME"]
print(list_good)
print(list_marginal)
print(list_nan)
print(list_poor)

#2

year = book_1[(book_1['INST_YEAR'] > 2000)]

print(year)
print(len(list_year))

#3

status = book_1[(book_1['STATUS'] == 'ACTIVE')]
light = book_1[(book_1['LIGHT'] == 'Yes')]
Walk = book_1[(book_1['WALKING'] == 'Yes')]
biking = Walk[(book_1['BIKING'] == 'Yes')]
print(len(status))
print(len(light))
print(len(biking))

#4
hike = book_1[(book_1['HIKING'] == 'Yes')]
biking = Walk[(book_1['BIKING'] == 'Yes')]
resultTuple = ()

for i, row in biking.iterrows():
  resultTuple = resultTuple + ((row["TRAIL_NAME"],row["CONDITION"],row["LIGHT"],row["STATUS"],row["HIKING"],row["BIKING"],row["ATV"]))

print(resultTuple)

"""# New Section"""