# -*- coding: utf-8 -*-
"""task00.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Gqftch5ll3CdBlU6mNLGNI4skOm1Fw-

fizzbuzzdemo-MimzeeGupta
"""

for nuM in range(1, 100):
  if nuM%3==0 | nuM%5==0:
    print("FizzBuzz")
  elif nuM%5==0:
    print("Buzz")
  elif nuM%3==0:
    print("Fizz")
  else:
    print(nuM)