# -*- coding: utf-8 -*-
"""task02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wHgMEi0aIY4gcwzilb2GGuuZkbUpDu7z
"""

# open both files
firstfile= open('first.txt','r')
secondfile = open('second.txt','w')
for line in firstfile:
    for i in line:
      if i=='o' or i=='O':
        a="0"
      elif i=='a' or i=='A':
        a="4"
      elif i=='e' or i=='E':
        a="3"
      elif i=='i' or i=="I":
        a="1"
      else:
        a=i
      secondfile.write(a)
secondfile=open("second.txt",'r')
content=secondfile.read()
print(content)